### ISSUE TITLE
[German] some book titles are not translated

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#19]
**PLATFORM and OS or BROWSER:**
windows tiles

**DCSS VERSION AND GAME INFORMATION:**
beta 4

**DESCRIPTION:**

looks like some book titles are not getting translated. I have not seen this this outside of this shop, but will stay on the lookout
**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/accb033f-b57e-4b4f-b468-6aaceca74519)

**Comment by powerbf** [comment]
Those names come from dat/database/randbook.txt. If we create a German version of that file, the game would generate German book names when playing in German. This is not ideal though, because if you switch language, the book names would stay in whatever language you were using when they were generated. Better would be to keep the internal names in English and translate for display. This is going to require some thought.

**Comment by powerbf** [comment]
Fixed in alphabet_soup-0.27 branch. The meaningful random book titles are now translated.

The nonsense random names are still not translated (same behaviour as on other artefacts).
